development:
  adapter: postgresql
  encoding: unicode
  database: ultimate_cycle_development
  pool: 5
  host: localhost
  username: ideesbebe
  password: sefsef

test:
  adapter: postgresql
  encoding: unicode
  database: ultimate_cycle_test
  host: localhost
  pool: 5
  username: ideesbebe
  password: sefsef

production:
  adapter: postgresql
  encoding: unicode
  database: ultimate_cycle_production
  host: localhost
  pool: 5
  username: ideesbebe
  password: sefsef