development:
  adapter: postgresql
  encoding: unicode
  database: ultimate_cycle_development
  pool: 5
  host: localhost
  username: sdiallo
  password: sdiallo88

test:
  adapter: postgresql
  encoding: unicode
  database: ultimate_cycle_test
  host: localhost
  pool: 5
  username: sdiallo
  password: sdiallo88

production:
  adapter: postgresql
  encoding: unicode
  database: ultimate_cycle_production
  host: localhost
  pool: 5
  username: sdiallo
  password: sdiallo88
