# Spree Editor TinyMCE Configuration
#
# These are the options that will automatically be passed into the tinyMCE.init function
# whenever TinyMCE is loaded in one of your spree pages. Please edit this file to
# customise your TinyMCE setup in your spree installation. If you wish to see the full
# range of configuration options then please go here:
#
#    http://www.tinymce.com/wiki.php/configuration

# TinyMCE Options
mode: "exact"
theme: "modern"
language: "<%= I18n.locale.to_s.split('-')[0].downcase %>"
skin: "lightgray"
schema: "html5-strict"
element_format: "html"
resize: true
plugins:
  - layer
  - table
  - insertdatetime
  - preview
  - searchreplace
  - contextmenu
  - paste
  - directionality
  - noneditable
  - visualchars
  - nonbreaking

# Each line is a toolbar
toolbar:
  - cut copy paste pastetext pasteword | search replace | undo redo | link unlink anchor cleanup code | insertdate inserttime preview | tablecontrols | hr removeformat
  - bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | sub sup | bullist numlist | outdent indent blockquote" | charmap media | visualchars blockquote
  - styleselect formatselect fontselect fontsizeselect | forecolor backcolor
